// DO NOT ADD CODE TO THIS FILE! THIS FILE IS GENERATED FROM THE BENCHMARK SCRIPT. 
// ANY CHANGES MADE TO THIS FILE WILL BE LOST.
#ifndef BUDDY_SIZE_H
#define BUDDY_SIZE_H

// Can be udpated for testing purposes
#define MAX_ALLOC_SIZE_BITS 4 // 2^4 = 16 bytes
#define MIN_ALLOC_SIZE_BITS 1 // 2^1 = 2 bytes

#define MIN_ALLOC_SIZE (1L << MIN_ALLOC_SIZE_BITS)
#define MAX_ALLOC_SIZE (1L << MAX_ALLOC_SIZE_BITS)

#endif // BUDDY_SIZE_H
